apiVersion: batch/v1
kind: Job
metadata:
  name: installplan-approver
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.4
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/approver
              echo "Approving operator install.  Waiting a few seconds to make sure the InstallPlan gets created first."
              sleep $SLEEP
              installplan=$(oc get installplan -n openshift-operators | grep -i cert-manager.v1.5.4 | awk '{print $1}'); echo "installplan: $installplan"
              
              count=0

              if [ "$installplan" != "" ]
                echo "patching install plan: $installplan"
                oc patch installplan ${installplan} -n openshift-operators --type merge --patch '{"spec":{"approved":true}}'

                until [[ oc get installplan $installplan -o jsonpath="{.spec.approved}" -n openshift-operators == "true" ]] || [[ $count -eq 10 ]] do
                  count=$((count + 1))
                  sleep 60
                done

              fi

              if [[ $count -eq 10 ]]; then
                echo "Timed out waiting for CertManager to installplan to be approved"
                exit 1
              fi
          imagePullPolicy: Always
          name: installplan-approver
          env:
            - name: SLEEP
              value: "2m"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: installplan-approver-job
      serviceAccountName: installplan-approver-job
      terminationGracePeriodSeconds: 30
