apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: cert-manager-webhook
webhooks:
  - name: webhook.cert-manager.io
    namespaceSelector:
      matchExpressions:
        - key: name
          operator: NotIn
          values:
            - ns
        - key: cert-manager.io/disable-validation
          operator: NotIn
          values:
            - "true"
